// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["marionette"], function(marionette) {
    var AppRouter, _ref;
    return AppRouter = (function(_super) {
      __extends(AppRouter, _super);

      function AppRouter() {
        this.initPushSate = __bind(this.initPushSate, this);
        this.initialize = __bind(this.initialize, this);
        _ref = AppRouter.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      AppRouter.prototype.appRoutes = {};

      AppRouter.prototype.initialize = function() {
        AppRouter.__super__.initialize.apply(this, arguments);
        this.initPushSate();
      };

      AppRouter.prototype.initPushSate = function() {
        $("body").on("click", "a:not([data-bypass])", function(event) {
          var href, protocol;
          href = $(event.currentTarget).attr('href');
          if (href === "#togglemenu") {
            return;
          }
          protocol = this.protocol + '//';
          if ((href != null ? href.slice(protocol.length) : void 0) !== protocol) {
            event.preventDefault();
            Backbone.history.navigate(href, {
              trigger: true
            });
          }
        });
      };

      AppRouter.prototype.controller = {};

      return AppRouter;

    })(marionette.AppRouter);
  });

}).call(this);
